{% set name = "cython-lint" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cython_lint-{{ version }}.tar.gz
  sha256: 87b0f2ebb479c7bbe5b8673b9affb092223ef651ae9b1761ccc048a61d964ef1

build:
  noarch: python
  entry_points:
    - cython-lint = cython_lint.cython_lint:main
    - double-quote-cython-strings = cython_lint.string_fixer:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cython >=0.29.32
    - pycodestyle
    - python >=3.6
    - tokenize-rt >=3.2.0

test:
  imports:
    - cython_lint
  commands:
    - pip check
    - cython-lint --help
    - double-quote-cython-strings --help
  requires:
    - pip

about:
  home: https://github.com/MarcoGorelli/cython-lint
  summary: A linter for Cython files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
