{% set name = "cython-lint" %}
{% set version = "0.16.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cython_lint-{{ version }}.tar.gz
  sha256: 829046988d3986443c47183e7ea567a6893d78dfb135144670ffff67d58deb9e

build:
  noarch: python
  entry_points:
    - cython-lint = cython_lint.cython_lint:main
    - double-quote-cython-strings = cython_lint.string_fixer:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - cython >=0.29.32
    - pycodestyle
    - tokenize-rt >=3.2.0
    - tomli

test:
  imports:
    - cython_lint
  commands:
    - pip check
    - cython-lint --help
    - double-quote-cython-strings --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MarcoGorelli/cython-lint
  summary: A linter for Cython files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
