schema_version: 1

context:
  name: cython-lint
  version: 0.16.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cython_lint-${{ version }}.tar.gz
  sha256: dea72b81fd7635733080c67f1c8258cff498a4ef5664e010f894585a7290d6ad

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - cython-lint = cython_lint.cython_lint:main
      - double-quote-cython-strings = cython_lint.string_fixer:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - python >=${{ python_min }}
    - cython >=0.29.32
    - pycodestyle
    - tokenize-rt >=3.2.0
    - tomli

tests:
  - python:
      imports:
        - cython_lint
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - cython-lint --help
      - double-quote-cython-strings --help

about:
  summary: A linter for Cython files
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/MarcoGorelli/cython-lint

extra:
  recipe-maintainers:
    - thewchan
